swagger: '2.0'
info:
  version: 0.0.1
  title: User info
  description: Basic information about current user
  contact: {}
  license:
    name: ''
host: 'proxy.api.dev.auckland.ac.nz'
schemes:
  - https
basePath: /user
tags:
  - name: user
    description: Basic information about user
paths:
  '/':
    get:
      tags:
        - user
      summary: Information about  user
      description: 'Application can use this endpoint to get authentication information - know who the current user is (id, name, email)'
      produces:
        - application/json
      responses:
        '200':
          description: User information
          schema:
            $ref: '#/definitions/User'
        '401':
          description: Unauthorized (not authenticated)
        '500':
          description: Unexpected error
      security:
        - identity_oauth_implicit: 
          - default
        - identity_oauth_authcode: 
          - default      
securityDefinitions:
  identity_oauth_implicit:
    type: oauth2
    authorizationUrl: 'https://pam.dev.auckland.ac.nz/user/oauth2/authorize'
    flow: implicit
    scopes:
      default: Basic user information
  identity_oauth_authcode:
    type: oauth2
    authorizationUrl: 'https://pam.dev.auckland.ac.nz/user/oauth2/authorize'
    tokenUrl: 'https://proxy.api.dev.auckland.ac.nz/user/oauth2/token'
    flow: accessCode
    scopes:
      default: Basic user information      
definitions:

  User:
    type: object
    required:
      - username
      - id
    properties:
      id:
        type: string
      name:
        type: string
      email:
        type: string
      username:
        type: string