swagger: '2.0'
info:
  version: 0.0.1
  title: Playground API
  description: |
    Test connectivity and authentication / authorization with this safe and fun API. You can 
    - Find `classes` based on `subject`, e.g. all *Biology* related classes.
    - Enroll youself into `classes`. 
    - See other students `enrollments`. 
    ### Implementing OAuth2 in your application
    First you need to provision credentials (client_id) for your application and register a callback endpoint.
    To retrieve `access_token`, redirect user to [authorize](https://pam.dev.auckland.ac.nz/playground/oauth2/authorize) endpoint to authenticate using University SSO and obtain authorization for accessing data within requested scopes. The `access_token` will be released to the callback registered on a step one. The token must be passed as `Authorization` header to all API requests which require it.
    
  contact: {}
  license:
    name: ''
host: 'proxy.api.dev.auckland.ac.nz'
schemes:
  - https
basePath: /playground
tags:
  - name: student
    description: personal data
  - name: class
    description: classes you can enrol into
  - name: enrollment
    description: classes a person is enrolled into
  - name: subject  
    description: subjects that are taught in here. each subject may have several classes
paths:
  /classes:
    get:
      tags:
        - class
      summary: Find classes that you can enroll into
      description: 'List of classes'
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: subjects
          in: query
          description: comma separated list of subjects. use subjects endpoint to get the list of available subjects
          required: false
          type: string
        - name: level
          in: query
          description: Chose from 1-5 
          required: false
          type: integer
          format: int32
        - name: size
          in: query
          description: results per page
          required: false
          type: integer
          format: int32
          default: 10          
        - name: from
          in: query
          description: results start from
          required: false
          type: integer
          format: int32
          default: 0
      responses:
        '200':
          description: list fo classes
          schema:
            $ref: '#/definitions/Classes'
        '400':
          description: Bad request
        '500':
          description: Unexpected error
  /subjects:
    get:
      tags:
        - subject
      summary: Get all available subjects
      description: 'List of available subjects'
      produces:
        - application/json
      responses:
        '200':
          description: List of available subjects
          schema:
            $ref: '#/definitions/Subjects'
        '500':
          description: Unexpected error
          
  '/students/{id}':
    get:
      tags:
        - student
      description: 'Returns student object'
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: upi of identity
          required: true
          type: string
      responses:
        '200':
          description: Student object
          schema:
            $ref: '#/definitions/Student'
        '400':
          description: Bad request (unsupported id)
        '401':
          description: Unauthorized (not authenticated)
        '404':
          description: Student not found
        '500':
          description: Unexpected error
      security:
        - playground_oauth_implicit: 
          - playground-read
        - playground_oauth_authcode: 
          - playground-read
          
  /students:
    get:
      tags:
        - class
        - student
      summary: Find students enrolled into classes
      description: 'Use `classId` to find all students enrolled into this class. Use `subject` to find all students enrolled into all classes for given subject'
      produces:
        - application/json
      parameters:
        - name: subject
          in: query
          description: subject (single value - search by multiple subjects is not supported). use subjects endpoint to get the list of available values
          required: false
          type: string
        - name: classId
          in: query
          description: class id
          required: false
          type: integer
          format: int64
        - name: size
          in: query
          description: results per page
          required: false
          type: integer
          default: 10
          format: int32
        - name: from
          in: query
          description: results start from
          required: false
          type: integer
          format: int32
          default: 0
      responses:
        '200':
          description: List of students who are enrolled into classes matching the search criterias
          schema:
            $ref: '#/definitions/Students'
        '400':
          description: Bad request
        '401':
          description: Unauthorized (not authenticated)          
        '500':
          description: Unexpected error    
      security:
        - playground_oauth_implicit: 
          - playground-read
        - playground_oauth_authcode: 
          - playground-read
          
  /enrollments:
    get:
      tags:
        - enrollment
      summary: Find students enrolled into classes
      description: 'Use `classId` parameter to get all enrollments into given class. Use `studentId` parameter to find all enrollments of particular student'
      produces:
        - application/json
      parameters:
        - name: subject
          in: query
          description: subject (single value - search by multiple subjects is not supported). use subjects endpoint to get the list of available subjects
          required: false
          type: string
        - name: classId
          in: query
          description: class id
          required: false
          type: integer
          format: int64
        - name: studentId
          in: query
          description: student id
          required: false
          type: string          
        - name: size
          in: query
          description: results per page
          required: false
          type: integer
          default: 10
          format: int32
        - name: from
          in: query
          description: results start from
          required: false
          type: integer
          format: int32
          default: 0
      responses:
        '200':
          description: List of enrollments records matching the search criteria
          schema:
            $ref: '#/definitions/Enrollments'
        '401':
          description: Unauthorized (not authenticated)            
        '400':
          description: Bad request
        '500':
          description: Unexpected error    
      security:
        - playground_oauth_implicit: 
          - playground-read
        - playground_oauth_authcode: 
          - playground-read
    post:
      tags:
        - enrollment
      summary: Enroll currently logged in user into class(es)
      description: 'Provide list of class ids to enroll current use into'
      produces:
        - application/json
      parameters:
        - name: classIds
          in: body
          description: ids of classes to enroll into 
          required: true
          schema:
            $ref: '#/definitions/ArrayOfIds'
      responses:
        '200':
          description: List of created enrollments
          schema:
            $ref: '#/definitions/Enrollments'
        '401':
          description: Unauthorized (not authenticated)            
        '400':
          description: Bad request
        '500':
          description: Unexpected error    
      security:
        - playground_oauth_implicit: 
          - playground-write
        - playground_oauth_authcode: 
          - playground-write 
          
  '/enrollments/{id}':
    get:
      tags:
        - enrollment
      description: 'Returns specific enrollment object'
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: id of enrollment
          required: true
          type: integer
          format: int64 
      responses:
        '200':
          description: Enrollment response
          schema:
            $ref: '#/definitions/Enrollment'
        '400':
          description: Bad request
        '401':
          description: Unauthorized (not authenticated)
        '404':
          description: Enrollment not found
        '500':
          description: Unexpected error
      security:
        - playground_oauth_implicit: 
          - playground-read
        - playground_oauth_authcode: 
          - playground-read          
    delete:
      tags:
        - enrollment
      description: 'Delete specific enrollment object. Only own enrollments can be deleted. Attempt to delete someone else enrollment will result in `403 Forbidden`'
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: id of enrollment
          required: true
          type: integer
          format: int64 
      responses:
        '200':
          description: Enrollment successfully deleted
        '400':
          description: Bad request
        '401':
          description: Unauthorized (not authenticated)
        '403':
          description: Forbidden (not allowed)
        '404':
          description: Enrollment not found
        '500':
          description: Unexpected error
      security:
        - playground_oauth_implicit: 
          - playground-write
        - playground_oauth_authcode: 
          - playground-write                    
securityDefinitions:
  playground_oauth_implicit:
    type: oauth2
    authorizationUrl: 'https://pam.dev.auckland.ac.nz/playground/oauth2/authorize'
    flow: implicit
    scopes:
      playground-read: Read student information or enrollment
      playground-write: Update student information or enrollment
  playground_oauth_authcode:
    type: oauth2
    authorizationUrl: 'https://pam.dev.auckland.ac.nz/playground/oauth2/authorize'
    tokenUrl: 'https://proxy.api.dev.auckland.ac.nz/playground/oauth2/token'
    flow: accessCode
    scopes:
      playground-read: Read student information or enrollment
      playground-write: Update student information or enrollment
      
definitions:

  ArrayOfIds:
    type: array
    items: 
      type: integer
      format: int64
      
  Class:
    type: object
    required:
      - name
      - id
      - subject
      - level
    properties:
      name:
        type: string
      subject:
        type: string
      level:
        type: integer
      id:
        type: integer
        
  Classes:
    type: object
    properties:
      from:
        type: integer
        format: int32
        description: Position in pagination.
      count:
        type: integer
        format: int32
        description: Total number of classes found.
      data:
        type: array
        items:
          $ref: '#/definitions/Class'
          
  Subjects:
    type: object
    properties:
      data:
        type: array
        items:
          type: string
          
  Student:
    type: object
    required:
      - displayName
      - id
    properties:
      id:
        type: string    
      displayName:
        type: string
      emailAddress:
        type: string
      firstName:
        type: string
      lastName:
        type: string        
      enrollments:
        type: array
        items:
          $ref: '#/definitions/Enrollment'

  Students:
    type: object
    properties:
      from:
        type: integer
        format: int32
        description: Position in pagination.
      count:
        type: integer
        format: int32
        description: Total number of students found.
      data:
        type: array
        items:
          $ref: '#/definitions/Student'        

  Enrollment:
    type: object
    required:
      - studentId
      - id
      - classId
    properties:
      classId:
        type: integer
        format: int64                
      id:
        type: integer
        format: int64
      studentId:
        type: string
        
  Enrollments:
    type: object
    properties:
      from:
        type: integer
        format: int32
        description: Position in pagination.
      count:
        type: integer
        format: int32
        description: Total number of enrollments found.
      data:
        type: array
        items:
          $ref: '#/definitions/Enrollment'        
        