swagger: '2.0'
info:
  version: 0.0.1
  title: Playground API
  description: Test connectivity and authentication / auhtorization with this safe and fun API
  contact: {}
  license:
    name: ''
host: 'proxy.api.dev.auckland.ac.nz'
schemes:
  - https
basePath: /playground
tags:
  - name: student
    description: personal data
  - name: class
    description: classes you can enrol into
  - name: enrollment
    description: classes a person is enrolled into
  - name: subject  
    description: subjects that are taught in here. each subject may have several classes
paths:
  /classes:
    get:
      tags:
        - class
      summary: Find classes that you can enroll into
      description: 'List of classes'
      operationId: searchByNameUsingGET
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: subject
          in: query
          description: subject. use subjects endpoint to get the list of available subjects
          required: false
          type: string
        - name: level
          in: query
          description: Chose from 1-5 
          required: false
          type: number
        - name: size
          in: query
          description: results per page
          required: false
          type: integer
          default: 10
          format: int32
        - name: from
          in: query
          description: results start from
          required: false
          type: integer
          format: int32
          default: 0
      responses:
        '200':
          description: list fo classes
          schema:
            $ref: '#/definitions/Classes'
        '400':
          description: Bad request
        '500':
          description: Unexpected error
  /subjects:
    get:
      tags:
        - subject
      summary: Get all subjects
      description: 'List of subjects'
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: list fo classes
          schema:
             type: array
             items:
              $ref: '#/definitions/Subject'
        '500':
          description: Unexpected error
          
  '/students/{id}':
    get:
      tags:
        - student
      description: 'Returns student object'
      operationId: getPersonByUpiUsingGET
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: upi of identity
          required: true
          type: string
      responses:
        '200':
          description: identity response
          schema:
            $ref: '#/definitions/Student'
        '400':
          description: Bad request (unsupported id)
        '401':
          description: Unauthorized
        '403':
          description: Unauthorized
        '404':
          description: Identity not found
        '500':
          description: Unexpected error
      security:
        - playground_oauth_implicit: 
          - playground-read
        - playground_oauth_authcode: 
          - playground-read
          
  /students:
    get:
      tags:
        - class
      summary: Find students enrolled into classes
      description: 'List of students'
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: subject
          in: query
          description: subject. use subjects endpoint to get the list of available subjects
          required: false
          type: string
        - name: class
          in: query
          description: class id
          required: false
          type: number
        - name: size
          in: query
          description: results per page
          required: false
          type: integer
          default: 10
          format: int32
        - name: from
          in: query
          description: results start from
          required: false
          type: integer
          format: int32
          default: 0
      responses:
        '200':
          description: list of students who are enrolled into classes matching the search parameters
          schema:
            $ref: '#/definitions/Students'
        '400':
          description: Bad request
        '500':
          description: Unexpected error    
      security:
        - playground_oauth_implicit: 
          - playground-read
        - playground_oauth_authcode: 
          - playground-read
          
  /enrollments:
    get:
      tags:
        - enrollment
      summary: Find students enrolled into classes
      description: 'List of enrollments'
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: subject
          in: query
          description: subject. use subjects endpoint to get the list of available subjects
          required: false
          type: string
        - name: class
          in: query
          description: class id
          required: false
          type: number
        - name: studentid
          in: query
          description: student id
          required: false
          type: number          
        - name: size
          in: query
          description: results per page
          required: false
          type: integer
          default: 10
          format: int32
        - name: from
          in: query
          description: results start from
          required: false
          type: integer
          format: int32
          default: 0
      responses:
        '200':
          description: list of enrollments matching the search criterias
          schema:
            $ref: '#/definitions/Enrollments'
        '400':
          description: Bad request
        '500':
          description: Unexpected error    
      security:
        - playground_oauth_implicit: 
          - playground-read
        - playground_oauth_authcode: 
          - playground-read
          
securityDefinitions:
  playground_oauth_implicit:
    type: oauth2
    authorizationUrl: 'https://pam.dev.auckland.ac.nz/playground/oauth2/authorize'
    flow: implicit
    scopes:
      playground-read: Read student information
  playground_oauth_authcode:
    type: oauth2
    authorizationUrl: 'https://pam.dev.auckland.ac.nz/playground/oauth2/authorize'
    tokenUrl: 'https://proxy.api.dev.auckland.ac.nz/playground/oauth2/token'
    flow: accessCode
    scopes:
      playground-read: Read student information
      
definitions:
  Class:
    type: object
    required:
      - name
      - id
      - subject
      - level
    properties:
      name:
        type: string
      subject:
        type: string
      level:
        type: integer
      id:
        type: integer
        
  Classes:
    type: object
    properties:
      from:
        type: integer
        format: int32
        description: Position in pagination.
      count:
        type: integer
        format: int32
        description: Total number of classes found.
      data:
        type: array
        items:
          $ref: '#/definitions/Class'


  Subject:
    type: object
    required:
      - name
    properties:
      name:
        type: string
        
  Student:
    type: object
    required:
      - displayName
      - id
    properties:
      displayName:
        type: string
      emailAddress:
        type: string
      firstName:
        type: string
      lastName:
        type: string        
      enrollmetn:
        type: array
        items:
          $ref: '#/definitions/Enrollment'
      id:
        type: integer
        format: int64
  Students:
    type: object
    properties:
      from:
        type: integer
        format: int32
        description: Position in pagination.
      count:
        type: integer
        format: int32
        description: Total number of students found.
      data:
        type: array
        items:
          $ref: '#/definitions/Student'        

  Enrollment:
    type: object
    required:
      - studentId
      - id
      - classId
    properties:
      classId:
        type: integer
        format: int64                
      id:
        type: integer
        format: int64
      studentId:
        type: integer
        format: int64     
        
  Enrollments:
    type: object
    properties:
      from:
        type: integer
        format: int32
        description: Position in pagination.
      count:
        type: integer
        format: int32
        description: Total number of enrollments found.
      data:
        type: array
        items:
          $ref: '#/definitions/Enrollment'        
        
